on: [push]
name: Lost Pixel Baseline Update

jobs:
  lost-pixel-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Cache Docusaurus build
        uses: actions/cache@v3
        with:
          path: |
            .docusaurus
            node_modules
          key: ${{ runner.os }}-docusaurus-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-docusaurus-

      - name: Build Docusaurus
        run: pnpm run build

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start Server
        run: pnpm run serve &

      - name: Wait for Server
        run: wait-on http://localhost:3000

      - name: Lost Pixel
        id: lp
        uses: lost-pixel/lost-pixel@v3.8.0
        env:
          LOST_PIXEL_MODE: update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        if: ${{ failure() && steps.lp.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update lost-pixel baselines
          delete-branch: true
          branch: 'lost-pixel-update/${{ github.ref_name }}'
          title: 'Lost Pixel update - ${{ github.ref_name }}'
          body: Automated baseline update PR created by Lost Pixel
